pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
        stage('Install Dependencies') {
            steps {
                bat 'pip install flask'
            }
        }
        stage('Test Application') {
            steps {
                bat 'python -m py_compile app.py'
            }
        }
        stage('Build Docker Image') {
            steps {
                bat 'docker build -t student-flask .'
            }
        }
        stage('Stop Old Container') {
            steps {
                bat 'docker stop student-app || exit /b 0'
                bat 'docker rm student-app || exit /b 0'
            }
        }
        stage('Deploy Application') {
            steps {
                bat 'docker run -d -p 5000:5000 --name student-app student-flask'
            }
        }
        stage('Verify Deployment') {
            steps {
                bat 'docker ps'
            }
        }
    }
}
